### ISSUE TITLE
What should i do to log into the local GTPS server after starting server.exe ?

### ISSUE THREAD

**Issue by QUERY-GANI** [RebillionXX/GTServer#3]
I have started the sql service and created a gtserver db and imported the sql file, what should I do next?

![image](https://user-images.githubusercontent.com/73988956/173258525-d0e10983-bbd4-44f7-94aa-e7ff325316f6.png)

i've tried to add my localhost ip address to hosts file:

```bash
0.0.0.0:17091 www.growtopia1.com
0.0.0.0:17091 www.growtopia2.com
0.0.0.0:17091 growtopia1.com
0.0.0.0:17091 growtopia2.com
```

but it still fails, and I tried to use the GTPS 3 server and login successfully, is there any configuration that needs to be added?

```bash
145.239.149.135 www.growtopia1.com
145.239.149.135 www.growtopia2.com
145.239.149.135 growtopia1.com
145.239.149.135 growtopia2.com
```

**Comment by RebillionXX** [comment]
**0.0.0.0** is **any ip** means you can use any public/forwarded ip from your machine and **17091** is enet service port. you should do it with
**your_ip growtopia1.com**
**your_ip growtopia2.com**
which is listening to http server
